### ISSUE TITLE
Not an issue - question on comparison

### ISSUE THREAD

**Issue by johndpope** [asanakoy/densepose-evolution#2]
do you have any pointers on comparing 2 videos of densepose.
Source a - chimp waves hand
source b - another chimpt waves hand - 
and then compare..
sorry to ask - your video popped up in top results when I google this.

**Comment by asanakoy** [comment]
Could you please clarify? I don't fully understand which comparison you want.

**Comment by johndpope** [comment]
If a dance move is similar from 2 different people
